require:
  - rubocop-performance
  - rubocop-rake

AllCops:
  Exclude:
    - 'vendor/**/*'
    - '.bundle/**/*'
    - 'Gemfile'
  SuggestExtensions: false
  DisplayCopNames: true
  TargetRubyVersion: 2.7

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

Performance/RedundantMerge:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Style/OptionalArguments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: no_comma
